[package]
name = "http-client"
version = "0.0.1"
authors = ["Laurent T. Fourrier <laurent@ltfourrier.net>"]
edition = "2024"

[features]
default = []
json = ["serde", "serde_json"]

[dependencies]
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
